name: "setup"
description: shared setup steps
inputs:
  rust:
    description: "Set to any truthy value to run Rust-related steps"
    required: false
    default: "true"
  node:
    description: "Set to any truthy value to run Node-related steps"
    required: false
    default: "true"

runs:
  using: composite
  steps:
  - if: ${{ fromJson(inputs.node) }}
    uses: actions/setup-node@v4
    with:
      node-version: "20"

  - if: ${{ fromJson(inputs.rust) }}
    name: Rust cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: |
        ${{ runner.os }}-cargo-

  - if: ${{ fromJson(inputs.node) }}
    name: Get npm cache directory
    id: npm-cache-dir
    shell: sh
    run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

  - if: ${{ fromJson(inputs.node) }}
    uses: actions/cache@v3
    with:
      path: ${{ steps.npm-cache-dir.outputs.dir }}
      key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-node-

  - uses: taiki-e/install-action@just

  - if: ${{ fromJson(inputs.rust) && fromJson(inputs.node) }}
    name: Setup wasm-pack
    uses: jetli/wasm-pack-action@v0.4.0
