[workspace]
members = [ "minty-cli", "minty-wasm","mintyml"]
resolver = "2"

[workspace.package]
license = "MIT"
repository = "https://github.com/youngspe/mintyml"
authors = ["Spencer Young"]
version = "0.1.18"

[profile.release]
strip = true
