set fallback

@default:
    just --list

install:
    npm install

wasm-pack *ARGS:
    wasm-pack build --no-pack {{ ARGS }}

build-wasm-web: (wasm-pack "-d" "pkg-web" "-t" "bundler")
    if [ ! -f pkg-node/minty_wasm.d.ts ]; then \
        mkdir -p pkg-node; \
        cp pkg-web/minty_wasm.d.ts pkg-node/minty_wasm.d.ts; \
    fi

build-wasm-node: (wasm-pack "-d" "pkg-node" "-t" "nodejs")

build-tsc:
    npx tsc -p tsconfig.build.json

test-exec:
    npx tsc -p tsconfig.test.json
    npx jest

publish-exec:
    npm publish

build:
    just build-node
