[package]
name = "mintyml"
description = "A minialist alternative syntax to HTML"
license = "MIT"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/youngspe/mintyml"

[dependencies.thiserror]
version = "1.0.57"
default-features = false
optional = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.either]
version = "1.9"
default-features = false

[dependencies.gramma]
version = "0.2"
default-features = false

[features]
default = ["std"]
std = ["gramma/std", "dep:thiserror"]
