name: Deploy MinTyML web demo

on:
  push:
    branches: [ "main" ]
    paths: 
      - ./web-demo
      - ./mintyml
      - ./minty-wasm
  workflow_dispatch:
    

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-pages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0

    - name: Build minty-wasm
      working-directory: minty-wasm
      run: |
        npm install
        npm run build-web

    - name: Build web-demo
      working-directory: web-demo
      run: |
        npm install
        npm run build
  
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./web-demo/dist/

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
