name: On-push actions

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - web-demo/**
      - mintyml/**
      - minty-wasm/**
  workflow_dispatch:
    inputs:
      changed_dirs:
        type: string
        default: '[".github","mintyml","minty-cli","minty-wasm","web-demo"]'

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ github.event_name != 'workflow_dispatch' && steps.changed_files.outputs.all_changed_files || inputs.changed_dirs || '[".github","mintyml","minty-cli","minty-wasm","web-demo"]' }}

    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        if: github.event_name != 'workflow_dispatch'
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          json: true
          escape_json: false

  on-push:
    runs-on: ubuntu-latest
    needs: get-changes
    env:
      update_core: ${{ contains(needs.get-changes.outputs.dirs, '"mintyml"') && '1' || '' }}
      update_cli: ${{ contains(needs.get-changes.outputs.dirs, '"minty-cli"') && '1' || '' }}
      update_node: ${{ contains(needs.get-changes.outputs.dirs, '"minty-wasm"') && '1' || '' }}
      update_demo: ${{ contains(needs.get-changes.outputs.dirs, '"web-demo"') && '1' || '' }}

    outputs:
      built_pages: ${{ env.update_core || env.update_node || env.update_demo }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Rust cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: taiki-e/install-action@just

    - name: Test mintyml crate
      if: env.update_core
      run: |
        just test-core

    - name: Test mintyml-cli crate
      if: env.update_core || env.update_cli
      run: |
        just test-core
