name: Rust

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - github/**
      - web-demo/**
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - github/**
      - web-demo/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
